### ISSUE TITLE
/put-respondent & /put-respondent-answers

### ISSUE THREAD

**Issue by andynataco** [dynata/rex-sdk-python#20]
Add functionality to create and update respondents. 
- [`/put-respondent`](https://developers.dynata.com/docs/rex-respondent-gateway/a56e2e87c1234-create-or-update-a-respondent)
- [`/put-respondent-answers`](https://developers.dynata.com/docs/rex-respondent-gateway/6605c416e1190-set-respondent-attributes)

**Comment by Santiago-Torres14** [comment]
@andynataco can you please write me a ticket for this one?
